server.port=${PORT:8082}
spring.application.name=vault_vintage

spring.datasource.url=${SPRING_DATASOURCE_URL:postgresql://postgres:lxTwTVDLCefftdLGtgVUxsMumyzDKkvu@postgres.railway.internal:5432/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vvintage}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vvintage123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
